# SPDX-FileCopyrightText: 2019-2026 Jochem Rutgers
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ".vscode/**"
SPDX-FileCopyrightText = "2019-2026 Jochem Rutgers"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "CHANGELOG.md"
SPDX-FileCopyrightText = "2019-2026 Jochem Rutgers"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "**/README*.md"
SPDX-FileCopyrightText = "2019-2026 Jochem Rutgers"
SPDX-License-Identifier = "CC-BY-4.0"
